# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JBZ CTF Team
email: CBgOEQQMMigWDxoHLCYWGjUvGgEYAwAERU0MAm0=
description:  We Criuz, che si owna di bello?

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jbzteam.github.io" # the base hostname & protocol for your site

github_username:  jbzteam
google_analytic_id:
disqus_name:
ctftime_username: jbz
ctftime_userid: 31388

permalink: /:categories/:title
paginate: 3
paginate_path: /page/:num

# jekyll seo tag settings
logo: assets/images/example-image.png
twitter:
username:

# Build settings
markdown: kramdown
sass:
style: compressed

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
